# Generated by Django 4.2.5 on 2023-09-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("original", models.URLField(verbose_name="Original URL")),
                ("shortcut", models.CharField(db_index=True, max_length=10, unique=True, verbose_name="Shortcut")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Date of creation")),
                ("last_accessed", models.DateTimeField(null=True, verbose_name="Date of last access")),
                ("use_count", models.PositiveIntegerField(default=0, verbose_name="Number of uses")),
            ],
        ),
    ]
